use crate::hyprland::ipc;
use serde::Serialize;

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HyprlandStatus {
    pub running: bool,
    pub instance: Option<String>,
}

#[tauri::command]
pub fn get_hyprland_status() -> HyprlandStatus {
    let instance = std::env::var("HYPRLAND_INSTANCE_SIGNATURE").ok();
    HyprlandStatus {
        running: instance.is_some(),
        instance,
    }
}

#[tauri::command]
pub async fn get_workspaces() -> Result<Vec<ipc::WorkspaceInfo>, String> {
    ipc::get_workspaces().await
}

#[tauri::command]
pub async fn get_active_window() -> Result<Option<ipc::ActiveWindowInfo>, String> {
    ipc::get_active_window().await
}

#[tauri::command]
pub async fn get_monitors() -> Result<Vec<ipc::MonitorInfo>, String> {
    ipc::get_monitors().await
}

#[tauri::command]
pub async fn switch_workspace(id: i32) -> Result<(), String> {
    ipc::switch_workspace(id).await
}

#[tauri::command]
pub async fn hypr_dispatch(action: String) -> Result<String, String> {
    ipc::dispatch(&action).await
}

#[tauri::command]
pub fn generate_hyprland_config() -> String {
    format!(
        r#"# eDEX-DE Hyprland Integration Config
# Add this to your hyprland.conf or source it:
#   source = ~/.config/edex-de/hyprland-integration.conf
#
# Generated by eDEX-DE — edit as needed

# ──────────────────────────────────────────────
# App Launcher (Alt+Space is handled by eDEX-DE itself via Tauri global shortcut)
# The Meta key launcher requires a Hyprland bind since Wayland apps
# cannot grab the Super key directly:
bind = SUPER, Space, exec, edex-de --launcher
# OR to send an IPC message to a running instance:
# bind = SUPER, Space, exec, edex-de-ipc toggle-launcher

# ──────────────────────────────────────────────
# eDEX-DE window rules — make it act as a desktop layer
# These rules target the Tauri WebKitGTK window by class/title

# Keep eDEX-DE on all workspaces (pinned)
windowrulev2 = pin, class:^(edex-de)$
windowrulev2 = pin, title:^(eDEX-DE)$

# No decorations
windowrulev2 = nodecor, class:^(edex-de)$
windowrulev2 = nodecor, title:^(eDEX-DE)$

# No borders
windowrulev2 = noborder, class:^(edex-de)$
windowrulev2 = noborder, title:^(eDEX-DE)$

# No shadows
windowrulev2 = noshadow, class:^(edex-de)$
windowrulev2 = noshadow, title:^(eDEX-DE)$

# Move to special workspace or layer — keep below normal windows
windowrulev2 = layer, bottom, class:^(edex-de)$

# Fullscreen (type 1 = maximized/fullscreen without gaps)
windowrulev2 = fullscreenstate, 1, class:^(edex-de)$

# No animation on eDEX-DE window (it has its own boot animation)
windowrulev2 = noanim, class:^(edex-de)$
windowrulev2 = noanim, title:^(eDEX-DE)$

# Keep on monitor 0 (change if you want it on a different monitor)
windowrulev2 = monitor 0, class:^(edex-de)$

# ──────────────────────────────────────────────
# Make eDEX-DE the wallpaper/desktop layer
# This moves it to workspace "special:desktop" which stays below all others
# Uncomment if you want it truly behind all windows:
# windowrulev2 = workspace special:desktop, class:^(edex-de)$

# ──────────────────────────────────────────────
# Keybindings for eDEX-DE features
bind = CTRL SHIFT, H, exec, edex-de --show-hyprland-config   # Show Hyprland config modal
bind = CTRL SHIFT, L, exec, edex-de --lock                   # Lock screen (fprintd/password)
bind = CTRL ALT, S, exec, edex-de --services                 # Jump to services panel

# ──────────────────────────────────────────────
# Startup: launch eDEX-DE on login
exec-once = edex-de

# ──────────────────────────────────────────────
# Recommended general Hyprland settings for eDEX-DE DE use:
# general {{
#   gaps_in = 0
#   gaps_out = 0
#   border_size = 1
#   col.active_border = rgba(00e5ffaa)
#   col.inactive_border = rgba(1a1a2eaa)
# }}
# decoration {{
#   rounding = 0
#   blur {{
#     enabled = true
#     size = 4
#   }}
# }}
"#
    )
}

#[tauri::command]
pub fn save_hyprland_integration_config() -> Result<String, String> {
    let config = generate_hyprland_config();

    let config_dir = dirs::config_dir()
        .ok_or("Cannot find config directory")?
        .join("edex-de");

    std::fs::create_dir_all(&config_dir).map_err(|e| e.to_string())?;

    let config_path = config_dir.join("hyprland-integration.conf");
    std::fs::write(&config_path, &config).map_err(|e| e.to_string())?;

    Ok(config_path.to_string_lossy().to_string())
}
